services:
  kafka:
    image: apache/kafka:4.2.0
    container_name: hmdp-kafka
    user: "0:0"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    restart: unless-stopped

volumes:
  kafka-data:
